services:
    nginx:
        image: nginx:latest
        container_name: "${PROJECT_NAME}-nginx"
        volumes:
            - "./:/var/www/html"
            - ".docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"
        depends_on:
            - php
        networks:
            - backend
        restart: always

    php:
        build:
            context: "./docker/php"
        container_name: "${PROJECT_NAME}-php"
        user: "${UID}:${GID}"
        volumes:
            - "./:/var/www/html"
        networks:
            - backend
        restart: always

    database:
        image: mysql:8.4.0
        container_name: "${PROJECT_NAME}-database"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
        ports:
            - "3306:3306"
        restart: always
        networks:
            - backend

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: "${PROJECT_NAME}-phpmyadmin"
        environment:
            PMA_HOST: database
            PMA_USER: "${MYSQL_ROOT_USER}"
            PMA_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        ports:
            - "8080:80"
        restart: always
        depends_on:
            - database
        networks:
            - backend

networks:
    backend:
        driver: bridge